development:
  adapter: mysql2
  database: for_kevin_dev
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: for_kevin_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: ENV['DATABASE']
  username: ENV['DB_USER']
  password: ENV['DB_PASSWORD']
  host: ENV['DB_HOST']
  pool: 5
